version: 1.0.{build}

environment:
  API_KEY:
    secure: YIuqOcciVmoaQJhMWRoknEDuDMTUJ+oMnHCXQmBlgv4=
    
install:
- ps: .\CreateDb.ps1 -JobName $env:APPVEYOR_JOB_NAME -masterCategory "C1" -AccountName $env:APPVEYOR_ACCOUNT_NAME -ProjectSlug "paralleltests-lo9hm" -ApiKey $env:API_KEY -branch $env:APPVEYOR_REPO_BRANCH -RepoCommit $env:APPVEYOR_REPO_COMMIT -TimeOutMins 1
- cmd: nuget restore

build:
  verbosity: minimal

test:
  categories:
  - - C1
  - - C2
  - - C3
  - - C4
